# Definindo as dependências, configurações do ambiente e os ativos do projeto.

name: vca_food
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  provider: ^6.0.0
  intl: ^0.19.0
  # shimmer: ^2.0.0
  # json_annotation: ^4.8.1
  # carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # build_runner: ^2.2.0
  # json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  assets:
    - assets/imagens/
    - assets/restaurantes.json
